### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by vzaliva** [mrichar1/clipster#100]
Trying to use clipster but it gives me some warnings. The reason I am trying it is to try to see if it could help
with sharing a screenshot from `flameshot` to Slack via clipboard. It does not.

```
$ ./clipster -d
./clipster:711: PyGIDeprecationWarning: GObject.io_add_watch is deprecated; use GLib.io_add_watch instead
  GObject.io_add_watch(self.sock, GObject.IO_IN,
./clipster:711: PyGIDeprecationWarning: GObject.IO_IN is deprecated; use GLib.IO_IN instead
  GObject.io_add_watch(self.sock, GObject.IO_IN,
./clipster:723: PyGIDeprecationWarning: GObject.timeout_add_seconds is deprecated; use GLib.timeout_add_seconds instead
  GObject.timeout_add_seconds(history_timeout,

./clipster:490: DeprecationWarning: Gdk.Display.get_pointer is deprecated
  while Gdk.ModifierType.BUTTON1_MASK & display.get_pointer().mask:
^C^C⏎
$ uname -a
Linux relic 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**Comment by mrichar1** [comment]
Hi,

These warnings are about deprecation of various methods in GTK - I try to update Clipster to run across a variety of up-to-date operating systems, but often the latest releases will report these warnings as they update their version of GTK. However, these are only warnings, not errors, and can be safely ignored, since the old functions still exist in the newer versions.

In terms of screenshots, clipster only stores copied text in its history. For other media types like images it just leaves them in the untouched in the clipboard.
