### ISSUE TITLE
Add pinning of history elements

### ISSUE THREAD

**Issue by andya9** [mrichar1/clipster#17]
This corresponds to #11 :  it would be useful being able to mark items as to-be-kept when deleting or cicling history

**Comment by mrichar1** [comment]
Hi - sorry for never replying to this directly - but it has been under consideration while extending the delete functionality in #11.

I can see that this would be a useful feature - but it would require a change to the format of the history file to provide a location to store this kind of metadata.

Please let me know if this issue is still important to you - if so I'll have a think about how to implement this in more detail.

**Comment by andya9** [comment]
No problem. 
It's not something I really need, just a neat feature that _could_ be useful — I think I saw it in KDE's default clipboard manager around that time (but I could be wrong).
If you don't need it yourself, just leave it be, really; nowadays I'm much more proficient with python, so maybe I could try to implement it myself and make a pull request. 
I looked a bit into the history file, and I think it could be implemented as a list of tuples with tuple[0] = content and tuple[1] = True/False. The delete command would only act if tuple[1] = False, and that should be all. 
If you like the idea, let me know, I can implement it one of these days; only thing, I'm concerned about possible performance issues from the increased complexity of the history file, but probably it'll be negligible?

**Comment by mrichar1** [comment]
Always happy to look over any PRs :)

The issue is not that the technical implementation is difficult - more that the choice of how to structure the history file is difficult.

Which of the following is 'better' in terms of ease of access, readability, performance, etc?

```
#A list of tuples (or lists):
self.daemon.boards['primary'][24] = ('cat', True)

# A list of flat dicts
self.daemon.boards['primary'][24] = { 'content: 'cat', 'pinned': True}

# A list of nested dicts (key = content, value = dict of attributes)
self.daemon.boards['primary'][24] = {'cat': {'pinned': True}}

# A list of lists, first item is value, second is attribute dict
self.daemon.boards['primary'][24] = ['cat', {'pinned': True}]

```

Some of these are quick and efficient, some are readable and easier to modify, but they all have pros and cons. There are almost certainly other variations, not to mention options that involve refactoring at a higher level!

Also bear in mind that the above can probably all be serialised to JSON - but that also needs considering (so things like NamedTuples are probably out before we start!))

Hopefully that gives some context as to why I've not yet implemented anything! Hopefully this doesn't put you off submitting a PR, but makes you aware that you'll need to argue a case for whatever structure you end up submitting! :smiley:

**Comment by andya9** [comment]
:smile: 
Only my opinion:
- list of nested dicts: the ugliest to access
- list of lists: no point, tuples perform much better, and we don't need the mutability of lists
- flat dicts or tuples: the two best options, IMO; tuples should perform much better though.
I think that this particular use case is excellent for tuples: we don't really need named keys because:
1. we have only two entries (content and pinned)
2. we don't need to share the json with other software (we could even use pickle then, maybe it's better for performance).
Tomorrow I'll code an implementation using tuples (it should be straightforward to swap to flat dicts anyway), so that I see if problems occur/other solutions are better

**Comment by mrichar1** [comment]
I generally agree - though with some concerns:

* Mutability - I think we do need this for setting and toggling the flags. Granted this can be done by replacing the entire tuple, but it seems a bit less nice to read?

```
# turn off pinning with a dict
a = { 'content': 'cat', 'pinned': True}
a['pinned'] = False

# turn off pinning with a list
a = ['cat', True]
a[1] = False

# turn off pinning with a tuple
a = ('cat', True)
a = (a[0], False)
```

I was curious as to the performance of each of these - and it seems that dict and list are about the same speed, while tuple is slower. However they are all close enough that I wouldn't worry about performance being a concernf or clipster - we should focus on readability and useability!

* Extensibility. While we only have one flag now, we might end up having more in future. Here, using a tuple means that you either have to initialise the tuple with all flags set, or replace the tuple with a longer one when a flag is first set. With lists this is easier as we can append flags, with dicts its even nicer as flags have names. But there is a performance hit with dicts.

3. As to the history file format - I chose JSON over pickle due to some issues with pickle and uinicode, exacerbated by using both python 2 and 3. JSON is also human-readable, and does provide for sharing with other (non-python) apps (even if it's not knowingly being used that way just now. Dicts are a standard type in JSON, while tuples require some conversion to and from lists.

So my gut feeling is that flat dicts is the right answer here - but I'm willing to be persuaded otherwise!

**Comment by andya9** [comment]
No, it's you who persuaded me 😛 😄 I'll try doing it with dicts, if performance is good anyway then we should definitely prefer them for readability. I'm surprised about tuples being slower 😕

**Comment by andya9** [comment]
Moving to a list of strings to a list of dicts is a bit more complicated than I thought, I'll take some time

**Comment by andya9** [comment]
I actually gave up trying; implementing it was more difficult than I thought, and in all this time I just never felt its need in real use. I'm closing the issue
