### ISSUE TITLE
Allow to set output delimiter

### ISSUE THREAD

**Issue by memeplex** [mrichar1/clipster#37]
This would be useful for dumping the output of the clipboard in a text editor friendly format:

1. json is not that.
2. The default `\n` is ambiguous since clipboard entries often contains `\n`
3. The -0 option is not text editor friendly.

Please allow delimiter specification (like `>>>>>>>`) in the config file and/or the CLI.

**Comment by memeplex** [comment]
See https://github.com/mrichar1/clipster/pull/38

**Comment by mrichar1** [comment]
Hi,

Thanks for your issue and PR - this is definitely a feature that's worth adding to clipster.

I decided that the marker option isn't quite the right way to go. Iit provides no way to specify a separator without the existing delim - for example if the clipboard contains `hello` and `world` you can't specify a space as the marker to get `hello world` - you'll always get some newlines/nuls.

Instead I have created a `-m|--delim` option which defaults to `\n`. This can be overridden with the marker, and the person setting the marker can decide whether or not to use newlines at that point. (--nul still works by just setting `delim` to `\0`.

Note: In order to pass in special characters on the command-line, you have to work round the shell wanting to consume them. In bash this can be done by using the following syntax: `--delim $'\n>>>>\n' - note the single quotes.

I've pushed this change to a `delim` branch: 78107a1df4dda7cf5119494683f627a34f0105e8

Please grab this branch and test it out and let me know if it does what you're looking for?

Thanks!

**Comment by memeplex** [comment]
Thank you! It's ok for me, in fact I implemented it that way at first but
then I opted for the alternative I submitted because I felt most people
would want a line oriented separator.

**Comment by mrichar1** [comment]
Thanks for pointing out the issue and helping resolve it! :+1: 

Merged into master: 2b04404
