### ISSUE TITLE
Fails to capture anything copied from Blender

### ISSUE THREAD

**Issue by gandalf3** [mrichar1/clipster#48]
Anything copied from [Blender](http://blender.org/) doesn't end up in clipster's history.
Blender works fine with clipit, so I suspect this is a clipster issue.

Debug output:

```
% clipster -d -l DEBUG              

** (clipster:6892): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-0jJrcSQjtc: Connection refused
DEBUG:Debugging Enabled.
DEBUG:Trying to read config file: /home/gandalf3/.config/clipster/clipster.ini
DEBUG:Merged config: [('active_selections', 'CLIPBOARD'), ('data_dir', '/home/gandalf3/.local/share/clipster'), ('default_selection', 'CLIPBOARD'), ('duplicates', 'no'), ('extract_emails', 'yes'), ('extract_patterns', 'no'), ('extract_uris', 'yes'), ('filter_classes', ''), ('history_file', '/home/gandalf3/.local/share/clipster/history'), ('history_size', '30'), ('history_update_interval', '60'), ('max_input', '50000'), ('pid_file', '/home/gandalf3/.local/share/clipster/clipster.pid'), ('row_height', '3'), ('smart_update', '1'), ('socket_file', '/home/gandalf3/.local/share/clipster/clipster_sock'), ('sync_selections', 'no'), ('write_on_change', 'no')]
DEBUG:Writing history file every 60 seconds
# Here I attempt to copy
DEBUG:owner-change event!
DEBUG:selection: CLIPBOARD
DEBUG:Selection in 'active_selections'
DEBUG:Client connection received.
# And here I run clipster -sc
DEBUG:Received: sig:SELECT, board:CLIPBOARD, count:0
```

**Comment by mrichar1** [comment]
Hi - thanks for reporting this!

I can firstly confirm that this definitely was a bug - though it is caused by an unusual way that `Blender` notified clipboard events.

My code was being conservative, and looking for modified targets when an owner-change event was handled. However for some reason `Blender` doesn't set these, so my code treated it as a no-op, and didn't actually update the clipboard.

I've modified the code (taking a lead from `clipit`) and now always try to read text from the clipboard first, and then deal with failures afterwards.

I've tested this out with `Blender` as well I can (I'm not a user) and `clipster` now seems to receive clipboard contents correctly (and other tests are still passing).

I've pushed this as release 1.0.2 - please let me know if this fixes things for you!

**Comment by gandalf3** [comment]
Wow, that was quick. That indeed seems to have fixed things, thanks!
