### ISSUE TITLE
Discard (strings only containing) whitespaces

### ISSUE THREAD

**Issue by chron-isch** [mrichar1/clipster#51]
Whilte using the primary clipboard it happends quite offen to me that I accidentialy mark way more than I actually want to in a console, or just simply move my mouse a little too much and send 2 or even more lines to the primary clipboard, padded by a whole lot of whitespaces.

It would be awesome if we could filter those extra whitespaces out. The difficult thing would be to not filter out too much.

I guess it could be done with patterns alone, I just wanted to know what you think about it.

**Comment by mrichar1** [comment]
Hi - thanks for this suggestion!

As you said, this can be achieved with patterns - I *think* for this use case you want something like:

` ^[ \t]*(.*?)[ \t]*$`

(You could also use `\s` which would also strip newlines).

The downside with patterns is that currently they only add the extracted pattern to the board, leaving the actual clipboard selection intact. I can see an argument that this should be configurable to replace the last item instead of being in addition to it.

Let me know if making this change would be useful enough, of if you still think that an explicit config option to toggle whitespace stripping is needed.

**Comment by chron-isch** [comment]
Hi, thanks for the quick answer!

I've tried and noticed that behaviour myself allready.

I really like your idea of making it configurable to replace the last item, it's way more versatile than a simple config option to strip whitespaces.

**Comment by mrichar1** [comment]
The latest release `1.0.4` now has a `pattern_as_selection` config option.

If set to true, this will make the pattern match be both the last item in the history, and also replace the clipboard buffer.

Combining this with the whitespace pattern above should hopefully do what you want.

Let me know if this solution fixes your problem.
