### ISSUE TITLE
clipster -s spits out warnings

### ISSUE THREAD

**Issue by magnetophon** [mrichar1/clipster#62]
I'm not sure if this is a bug, but wanted to pass the info anyway.
When I run ``clipster -s`` in the terminal, I get 18 times:
```
(.clipster-wrapped:4373): Gtk-WARNING **: Allocating size to GtkDialog 0x213ff40 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

```

**Comment by mrichar1** [comment]
Hi - thanks for this report. 

Apparently this is a bug in Gtk, which appeared around 3.20 and has (allegedly) been in fixed in 3.22.

See https://bugzilla.gnome.org/show_bug.cgi?id=769566 and https://bugzilla.gnome.org/show_bug.cgi?id=773814

Fix is probably this commit: https://git.gnome.org/browse/gtk%2B/commit/?id=f3f71ef

I don't have a box with the latest Gtk around to test this (my current box only has 3.18, so I haven't seen that bug yet).

Going to close this as it looks like an upstream bug - thanks for letting me know about it anyway!
