### ISSUE TITLE
dmenu support?

### ISSUE THREAD

**Issue by bennylb** [mrichar1/clipster#7]
This is by far one of the lightest clipboard managers available for X. How hard would it be add dmenu support. If you could give me somewhere to start I could probably give it a go myself and then create pull request.

**Comment by mrichar1** [comment]
Hi,

I like the idea - but it will need a little bit of thinking over due to the way the client accesses the history through the daemon. I'll look at it and see if I can come up with a nice way of doing it.

In the short-term, you can at least 'proof-of-concept' it by running:

    clipster -p |dmenu |clipster -c

Which should present dmenu with a single item in it, then write the selected item back to the other clipboard history.

**Comment by bennylb** [comment]
Sounds brilliant. I'll give the POC a try. Let me know if I can do anything.
Cheers

**Comment by mrichar1** [comment]
I've got it partly working, but have discovered some bugs to do with handling STDIN when chaining clipster - such that the POC above won't work taking the output of dmenu back into clipster. I'll try and get the bugs ironed out then apply the patch for the original feature request.

**Comment by bennylb** [comment]
clipster in combination with dmenu will be a great combo.

**Comment by mrichar1** [comment]
I've now refactored clipster and added a `-o` option (rather than just returning the clipboard history if no arguments were passed).

As a result, you should now be able to run: `clipster -o 10` to get the last 10 items in the clipboard history sent to STDOUT.

Note that by default these items have newline (\n) as the delimiter, which dmenu/rofi expect. However I don't think they work very nicely if the clipboard entry itself contains newlines.

I have added a `-0` option, which used the `NUL` character as the delimiter to work around this - I don't know if either dmenu or rofi support this, but it would at least allow you to do some transforming of the output before passing it into dmenu to strip out all newlines from the clipboard entries, then replace the `NUL`s with newlines.

Please can you try this out and let me know what you think? Note that I fully expect that things will go badly wrong if newlines are involved, especially when not at the end of the selection, and lots of sed/tr might be needed!

``` bash
# Push some words to the clipboard:
~$ for i in one two three; do echo -n "$i" | clipster ; done

# Read back those words from the clipboard, pipe to dmenu, pipe back to clipster
# (Remove trailing newline)
~$ clipster -o 3 | dmenu | tr -d '\n'| clipster
```

**Comment by bennylb** [comment]
This is a quick and abominable attempt purely for the testing of changes you've made for demu/rofi support.

```bash
#!/bin/sh

entries="$(clipster -o --nul -n 15 | sed -e 's/\x0/\x0\x0/g' | tr '\n' '\000' | sed -e 's/\x0\{2\}/\n/g' -e 's/\x0/\x9/g')";
selection="$(rofi -dmenu -p 'clipster:' <<< "$entries")";
restored_selection="$(tr '\011' '\n' <<< "$selection")";
clipster -c <<< "$restored_selection"$'\0';
```
Let me what your thoughts are.

Cheers,

Ben

**Comment by mrichar1** [comment]
Scary! :) But yes, that does demonstrate a way of using NULs to handle newlines for things like dmenu/rofi.

If you're happy with this behaviour, please close this issue - otherwise if there are any other changes you think would help here, please add another comment or open a new issue if it's a suitably different feature.

**Comment by mrichar1** [comment]
Having been focused on dmenu, I'd not really looked into rofi that much - and I just discovered it has a `-sep` option.

Try out the following (`-eh` sets the line height bigger so you can see included newlines):

`clipster -o 3 -0 | rofi -dmenu -sep '\x00' -eh 5`

**Comment by bennylb** [comment]
I actually looked at the dmenu man page for separators/delimiters specifically but never thought to check the rofi man. I'll give it a go.

**Comment by bennylb** [comment]
Thanks for pointing that out. That's a hell of a lot cleaner. Closing. Thanks again.
