### ISSUE TITLE
Question: does it support pictures?

### ISSUE THREAD

**Issue by cytopia** [mrichar1/clipster#71]
Does clipster support copying pictures (jpeg, png, etc) to clipboard, or even select and copy a region from Gimp?

**Comment by mrichar1** [comment]
Clipster doesn't stop the copying of non-text items, but it doesn't attempt to store them in its history - mostly due to the difficulties in storing binary blobs, and not having an easy way to identify and restore them if you're not using the GUI.

It could be possible - it would just be a lot of work!
