### ISSUE TITLE
Del key not deleting all the selected items

### ISSUE THREAD

**Issue by yegorius** [mrichar1/clipster#73]
Some time ago I was able to clean all the items in the list buy pressing Ctrl-A + Del, but since recently Del doesn't delete all the selected items in the clipster GUI. It is a very convenient way to cleanup the history on demand.

**Comment by mrichar1** [comment]
Hi - this sounds like another unintended feature added by using the Gnome UI tools - and one which has broken, though I'm not sure why!

I'd like to tie this in to #36 which covers general UI improvements, since it probably comes down to a UI default or simialr being misconfigured. However I'm unfortunately short on time just now, so I'll have to add 'help wanted' tag to this, as with the other, to see if someone else has a chance to debug it.

If you do have some time to debug the issue, bisecting the releases and finding the regression would be very handy! (It's harder for me to do since testing the UI for each release is currently a manual process).
