### ISSUE TITLE
deprecation warnings when running the deamon

### ISSUE THREAD

**Issue by riscie** [mrichar1/clipster#93]
Hi there 

I am not sure whats wrong here. I get these warnings when starting the daemon or when trying to access the history

```
./clipster.py:707: PyGIDeprecationWarning: GObject.io_add_watch is deprecated; use GLib.io_add_watch instead
  GObject.io_add_watch(self.sock, GObject.IO_IN,
./clipster.py:707: PyGIDeprecationWarning: GObject.IO_IN is deprecated; use GLib.IO_IN instead
  GObject.io_add_watch(self.sock, GObject.IO_IN,
./clipster.py:719: PyGIDeprecationWarning: GObject.timeout_add_seconds is deprecated; use GLib.timeout_add_seconds instead
  GObject.timeout_add_seconds(history_timeout,
```

I am on arch with python 3.8.1. Is the python version maybe not supported yet?

**Comment by mrichar1** [comment]
Thanks for flagging this up. These are just warnings, not errors and are safe to ignore. 

The underlying GTK libraries that clipster uses have been updated, and and some of the methods clipster uses have been deprecated. This means tht they work for now, but will go away at some point.

You are probably seeing this due to being on an up-to-date system - I'll need to check when the new methods were added before I update the code, since otherwise clipster will stop working on older OSes which still have older versions of GTK.

**Comment by riscie** [comment]
I see. Thanks for the quick reply!
